unit Unit1;

interface

uses
  SysUtils, Classes, DB, ADODB;

type
  TDataModule1 = class(TDataModule)
    ADOConnection1: TADOConnection;
    ADOUlisi: TADOTable;
    DSUlisi: TDataSource;
    ADOJiteli: TADOTable;
    DSJiteli: TDataSource;
    ADOHoz_kniga: TADOTable;
    DSHoz_kniga: TDataSource;
    ADONalogPU: TADOTable;
    DSNalogPU: TDataSource;
    ADOSelo: TADOTable;
    DSSelo: TDataSource;
    ADOSeloID_Selo: TAutoIncField;
    ADOSeloNazvanie: TStringField;
    ADONasionalnost: TADOTable;
    DSNasionalnost: TDataSource;
    ADOLgoti: TADOTable;
    DSLgoti: TDataSource;
    ADOObrazovanie: TADOTable;
    DSObrazovanie: TDataSource;
    ADONasionalnostID_Nasionalnost: TAutoIncField;
    ADONasionalnostNasionalnost: TStringField;
    ADOLgotiID_Lgoti: TAutoIncField;
    ADOLgotiKategoria_lgot: TStringField;
    ADOObrazovanieID_Obrazovanie: TAutoIncField;
    ADOObrazovanieObrazovanie: TStringField;
    ADOKrest_hoz: TADOTable;
    DSKrest_hoz: TDataSource;
    ADOVid_zemli: TADOTable;
    DSVid_zemli: TDataSource;
    ADOHoz_subekt: TADOTable;
    DSHoz_subekt: TDataSource;
    ADOVid_Hoz_subekta: TADOTable;
    DSVid_Hoz_subekta: TDataSource;
    ADOVid_deatelnosti: TADOTable;
    DSVid_deatelnosti: TDataSource;
    ADOVid_Hoz_subektaID_Vid_xoz_sub: TAutoIncField;
    ADOVid_Hoz_subektaVid: TStringField;
    ADOSNalogPU: TADOTable;
    DSSNalogPU: TDataSource;
    ADOSNalogPUID_SNalogPU: TAutoIncField;
    ADOSNalogPUStavka: TFloatField;
    ADOSNalogPUInfo: TStringField;
    ADONomer_doma: TADOTable;
    DSNomer_doma: TDataSource;
    ADOKrest_hozID_Kr_hoz: TAutoIncField;
    ADOKrest_hozNazvanie: TStringField;
    ADOKrest_hozAdres: TStringField;
    ADOKrest_hozID_Jiteli: TIntegerField;
    ADOKrest_hozID_Selo: TIntegerField;
    ADOKrest_hozID_Ulisi: TIntegerField;
    ADOKrest_hozID_Nomer_doma: TIntegerField;
    ADOKrest_hozID_Vid_zemli: TIntegerField;
    ADOKrest_hozPloshad: TFloatField;
    ADOUlisiID_Ulisi: TAutoIncField;
    ADOUlisiNazvanie: TStringField;
    ADOQJiteli: TADOQuery;
    DSQJiteli: TDataSource;
    ADOSNalogSH: TADOTable;
    DSSNalogSH: TDataSource;
    ADOVid_zemliID_Vid_zemli: TAutoIncField;
    ADOVid_zemliVid: TStringField;
    ADOVid_zemliStavka: TFloatField;
    ADOSNalogSHID_SNalogSH: TAutoIncField;
    ADOSNalogSHInfo: TStringField;
    ADONalogSH: TADOTable;
    DSNalogSH: TDataSource;
    ADOVid_avto: TADOTable;
    DSVid_avto: TDataSource;
    ADOSrok_ekspluatasii_avto: TADOTable;
    DSSrok_ekspluatasii_avto: TDataSource;
    ADOStavka_avto: TADOTable;
    DSStavka_avto: TDataSource;
    ADONalogSHID_Nalog_sh_naznach: TAutoIncField;
    ADONalogSHID_Jiteli: TIntegerField;
    ADONalogSHID_Vid_zemli: TIntegerField;
    ADONalogSHID_Kr_hoz: TIntegerField;
    ADONalogSHSumma: TFloatField;
    ADONalogSHNPProsh: TFloatField;
    ADONalogSHOplata: TFloatField;
    ADONalogSHItigo: TFloatField;
    ADONalogSHNPSled: TFloatField;
    ADONalogSHData_oplati: TDateTimeField;
    ADOStavka_avtoID_Stavka_avto: TAutoIncField;
    ADOStavka_avtoID_Vid_avto: TIntegerField;
    ADOStavka_avtoID_Srok_eksp: TIntegerField;
    ADOStavka_avtoStavka: TFloatField;
    ADOStavka_avtoSrok: TStringField;
    ADOStavka_avtoVid: TStringField;
    ADOSNalogAvto: TADOTable;
    DSSNalogAvto: TDataSource;
    ADOSNalogAvtoID_SNalogAvto: TAutoIncField;
    ADOSNalogAvtoID_Stavka_avto: TIntegerField;
    ADOSNalogAvtoInfo: TStringField;
    ADOMarka_avto: TADOTable;
    DSMarka_avto: TDataSource;
    ADOVid_avtoID_Vid_avto: TAutoIncField;
    ADOVid_avtoVid: TStringField;
    ADOMarka_avtoID_Marka_avto: TAutoIncField;
    ADOMarka_avtoMarka: TStringField;
    ADOMarka_avtoID_Vid_avto: TIntegerField;
    ADOAvto: TADOTable;
    DSAvto: TDataSource;
    ADOUlisiID_Selo: TIntegerField;
    ADONomer_domaID_Nomer_doma: TAutoIncField;
    ADONomer_domaNomer_doma: TStringField;
    ADONalogAvto: TADOTable;
    DSNalogAvto: TDataSource;
    ADONalogPUID_Nalog_pr_uchastok: TAutoIncField;
    ADONalogPUID_Selo: TIntegerField;
    ADONalogPUID_Ulisi: TIntegerField;
    ADONalogPUID_Nomer_doma: TIntegerField;
    ADONalogPUID_Hoz_kniga: TIntegerField;
    ADONalogPUID_Lgoti: TIntegerField;
    ADONalogPUID_SNalogPU: TIntegerField;
    ADONalogPUSumma: TFloatField;
    ADONalogPUNPProsh: TFloatField;
    ADONalogPUItogo: TFloatField;
    ADONalogPUOplocheno: TFloatField;
    ADONalogPUNPSled: TFloatField;
    ADONalogPUData_oplati: TStringField;
    ADOHoz_knigaID_Hoz_kniga: TAutoIncField;
    ADOHoz_knigaHozain: TStringField;
    ADOHoz_knigaID_Selo: TIntegerField;
    ADOHoz_knigaID_Ulisi: TIntegerField;
    ADOHoz_knigaID_Nomer_doma: TIntegerField;
    ADOHoz_knigaID_Lgoti: TIntegerField;
    ADOHoz_knigaPriusad_uchastok: TFloatField;
    ADOSrok_ekspluatasii_avtoID_Srok_eksp: TAutoIncField;
    ADOSrok_ekspluatasii_avtoSrok_ekspluatasii: TStringField;
    ADOSrok_ekspluatasii_avtoID_Vid_avto: TIntegerField;
    ADOAvtoID_Selo: TIntegerField;
    ADOAvtoID_Ulisi: TIntegerField;
    ADOAvtoID_Nomer_doma: TIntegerField;
    ADOAvtoID_Vid_avto: TIntegerField;
    ADOAvtoID_Marka_avto: TIntegerField;
    ADOAvtoGos_nomer: TStringField;
    ADOAvtoGod_vipuska: TFloatField;
    ADOAvtoObem_dvigatela: TFloatField;
    ADOAvtoID_Avto: TAutoIncField;
    ADOAvtoID_Jiteli: TIntegerField;
    ADOAvtoID_Lgoti: TIntegerField;
    ADONalogAvtoID_Nalog_avto: TAutoIncField;
    ADONalogAvtoID_Jiteli: TIntegerField;
    ADONalogAvtoID_Lgoti: TIntegerField;
    ADONalogAvtoID_Selo: TIntegerField;
    ADONalogAvtoID_Ulisi: TIntegerField;
    ADONalogAvtoID_Nomer_doma: TIntegerField;
    ADONalogAvtoID_Avto: TIntegerField;
    ADONalogAvtoID_Marka_avto: TIntegerField;
    ADONalogAvtoID_Stavka_avto: TIntegerField;
    ADONalogAvtoSumma: TFloatField;
    ADONalogAvtoNPProsh: TFloatField;
    ADONalogAvtoItogo: TFloatField;
    ADONalogAvtoOpata: TFloatField;
    ADONalogAvtoNPSled: TFloatField;
    ADONalogAvtoData_oplati: TStringField;
    ADOQuery1: TADOQuery;
    DataSourse1: TDataSource;
    ADOSNalogR: TADOTable;
    DSSNalogR: TDataSource;
    ADOSNalogRID_SNalogR: TAutoIncField;
    ADOSNalogRInfo: TStringField;
    ADOSNalogRStavka: TFloatField;
    ADONalogR: TADOTable;
    DSNalogR: TDataSource;
    ADONalogRID_Nalog_reklama: TAutoIncField;
    ADONalogRID_SNalogR: TIntegerField;
    ADONalogRID_Hoz_sub: TIntegerField;
    ADONalogRID_Vid_deat: TIntegerField;
    ADONalogRKrat_Soderjanie: TStringField;
    ADONalogRStoimost: TFloatField;
    ADONalogRSumma: TFloatField;
    ADONalogROplata: TFloatField;
    ADONalogRData_oplati: TDateTimeField;
    ADONalogRData_razmeshenia: TDateTimeField;
    ADONalogRProdoljitelnost: TStringField;
    ADONalogRID_Jiteli: TIntegerField;
    ADOHoz_subektID_Hoz_sub: TAutoIncField;
    ADOHoz_subektID_Vid_hoz_sub: TIntegerField;
    ADOHoz_subektID_Vid_deat: TIntegerField;
    ADOHoz_subektNazvanie: TStringField;
    ADOHoz_subektID_Jiteli: TIntegerField;
    ADOHoz_subektINN: TStringField;
    ADOHoz_subektAdres: TStringField;
    ADOHoz_subektID_Selo: TIntegerField;
    ADOHoz_subektID_Ulisi: TIntegerField;
    ADOHoz_subektID_Nomer_doma: TIntegerField;
    ADOHoz_subektPloshad: TFloatField;
    ADOHoz_subektViruchka: TFloatField;
    ADOHoz_subektRol_rabochih: TLargeintField;
    ADOHoz_subektDop_deat: TStringField;
    ADOVid_deatelnostiID_Vid_deat: TAutoIncField;
    ADOVid_deatelnostiVid_deat: TStringField;
    ADOVid_deatelnostiK1: TFloatField;
    ADOVid_deatelnostiK2: TFloatField;
    ADOVid_deatelnostiK3: TFloatField;
    ADOSNalogNSH: TADOTable;
    DSSNalogNSH: TDataSource;
    ADOSNalogNSHID_Nalog_NSH: TAutoIncField;
    ADOSNalogNSHStavka: TFloatField;
    ADOSNalogNSHInfo: TStringField;
    ADONalogNSH: TADOTable;
    DSNalogNSH: TDataSource;
    ADONalogNSHID_Nalog_ne_sh_naznach: TAutoIncField;
    ADONalogNSHID_Hoz_sub: TIntegerField;
    ADONalogNSHID_SNalogNSH: TIntegerField;
    ADONalogNSHNPProsh: TFloatField;
    ADONalogNSHSumma: TFloatField;
    ADONalogNSHItogo: TFloatField;
    ADONalogNSHOplata: TFloatField;
    ADONalogNSHData_oplati: TDateTimeField;
    ADONalogNSHNPSled: TFloatField;
    ADONalogNSHID_Jiteli: TIntegerField;
    ADONalogNSHID_Vid_deat: TIntegerField;
    ADOSNalog4: TADOTable;
    DSSNalog4: TDataSource;
    ADOSNalog4ID_SNalog4: TAutoIncField;
    ADOSNalog4Stavka: TBCDField;
    ADOSNalog4Info: TStringField;
    ADONalog4: TADOTable;
    DSNalog4: TDataSource;
    ADONalog4ID_Nalog_s_prodaj: TAutoIncField;
    ADONalog4ID_SNalog4: TIntegerField;
    ADONalog4ID_Hoz_sub: TIntegerField;
    ADONalog4ID_Jiteli: TIntegerField;
    ADONalog4ID_Vid_deat: TIntegerField;
    ADONalog4Summa_NDS: TBCDField;
    ADONalog4Viruchka_bez_NDS: TBCDField;
    ADONalog4NPProsh: TBCDField;
    ADONalog4Summa: TBCDField;
    ADONalog4Itogo: TBCDField;
    ADONalog4Oplata: TBCDField;
    ADONalog4Data_oplati: TDateTimeField;
    ADONalog4NPSled: TBCDField;
    ADOSNalogMU: TADOTable;
    DSSNalogMU: TDataSource;
    ADOSNalogMUID_SNalogMU: TAutoIncField;
    ADOSNalogMUStavka: TBCDField;
    ADOSNalogMUInfo: TStringField;
    ADONalogMU: TADOTable;
    DSNalogMU: TDataSource;
    ADONalogMUID_Nalog_musor_ur: TAutoIncField;
    ADONalogMUID_SNalogMU: TIntegerField;
    ADONalogMUID_Hoz_sub: TIntegerField;
    ADONalogMUID_Jiteli: TIntegerField;
    ADONalogMUID_Vid_deat: TIntegerField;
    ADONalogMUNPProsh: TBCDField;
    ADONalogMUSumma: TBCDField;
    ADONalogMUItogo: TBCDField;
    ADONalogMUOplata: TBCDField;
    ADONalogMUData_oplati: TDateTimeField;
    ADONalogMUNPSled: TBCDField;
    ADOSNalogMF: TADOTable;
    DSSNalogMF: TDataSource;
    ADOSNalogMFID_NalogMF: TAutoIncField;
    ADOSNalogMFStavka: TBCDField;
    ADOSNalogMFInfo: TStringField;
    ADONalogMF: TADOTable;
    DSNalogMF: TDataSource;
    ADONalogMFID_Nalog_musor_fiz: TAutoIncField;
    ADONalogMFID_NalogMF: TIntegerField;
    ADONalogMFID_Selo: TIntegerField;
    ADONalogMFID_Ulisi: TIntegerField;
    ADONalogMFID_Nomer_doma: TIntegerField;
    ADONalogMFID_Hoz_kniga: TIntegerField;
    ADONalogMFID_Jiteli: TIntegerField;
    ADONalogMFNPProsh: TBCDField;
    ADONalogMFSumma: TBCDField;
    ADONalogMFItogo: TBCDField;
    ADONalogMFOplata: TBCDField;
    ADONalogMFData_oplati: TStringField;
    ADONalogMFNPSled: TBCDField;
    ADONalogMFKol_16: TIntegerField;
    ADOQUlisi: TADOQuery;
    DSQUlisi: TDataSource;
    ADOQJiteliFIO: TStringField;
    ADOQJiteliID_Jiteli: TAutoIncField;
    ADOQKHoz: TADOQuery;
    DSQKHoz: TDataSource;
    ADOQKHozID_Kr_hoz: TAutoIncField;
    ADOQKHozNazvanie: TStringField;
    DSQHSub: TDataSource;
    ADOQHSub: TADOQuery;
    ADOQHSubID_Hoz_sub: TAutoIncField;
    ADOQHSubNazvanie: TStringField;
    ADOQuery1Marka: TStringField;
    ADOQuery1FIO: TStringField;
    ADOQuery1ID_Avto: TAutoIncField;
    ADOQuery1ID_Marka_avto: TAutoIncField;
    ADOQuery1ID_Jiteli: TAutoIncField;
    ADOQuery1Vid: TStringField;
    ADOQVidA: TADOQuery;
    DSQVidA: TDataSource;
    ADOQVidAVid: TStringField;
    ADOQVidAMarka: TStringField;
    ADONomer_domaID_Ulisi: TIntegerField;
    ADOQUlisiSelo: TStringField;
    ADOQUlisiUlisa: TStringField;
    ADOQDom: TADOQuery;
    DSQDom: TDataSource;
    ADOQDomNazvanie: TStringField;
    ADOQDomID_Ulisi: TAutoIncField;
    ADOQDomNomer_doma: TStringField;
    ADOQDomID_Nomer_doma: TAutoIncField;
    ADOJiteliID_Jiteli: TAutoIncField;
    ADOJiteliFIO: TStringField;
    ADOJiteliPol: TStringField;
    ADOJiteliData_rojdenia: TDateTimeField;
    ADOJiteliPasport_dannie: TStringField;
    ADOJiteliGraldansvo: TStringField;
    ADOJiteliMesto_uchebi: TStringField;
    ADOJiteliMesto_raboti: TStringField;
    ADOJiteliID_Selo: TIntegerField;
    ADOJiteliID_Ulisi: TIntegerField;
    ADOJiteliID_Lgoti: TIntegerField;
    ADOJiteliRodst_otnoshenia: TStringField;
    ADOJiteliID_Nasionalnost: TIntegerField;
    ADOJiteliID_Obrazovanie: TIntegerField;
    ADOJiteliID_Nomer_doma: TIntegerField;
    ADOKrest_hozAdres2: TStringField;
    ADOKrest_hozFIO2: TStringField;
    ADOHoz_subektFIO2: TStringField;
    ADOHoz_subektAdres2: TStringField;
    ADONalogSHIS_Selo: TIntegerField;
    ADONalogSHID_Ulisi: TIntegerField;
    ADONalogSHID_Nomer_doma: TIntegerField;
    ADONalogNSHID_Selo: TIntegerField;
    ADONalogNSHID_Ulisi: TIntegerField;
    ADONalogNSHID_Nomer_doma: TIntegerField;
    ADONalog4ID_Selo: TIntegerField;
    ADONalog4ID_Ulisi: TIntegerField;
    ADONalog4ID_Nomer_doma: TIntegerField;
    ADONalogMUID_Selo: TIntegerField;
    ADONalogMUID_Ulisi: TIntegerField;
    ADONalogMUID_Nomer_doma: TIntegerField;
    ADONalogRID_Selo: TIntegerField;
    ADONalogRID_Ulisi: TIntegerField;
    ADONalogRID_Nomer_doma: TIntegerField;
    ADOQSHO: TADOQuery;
    DSQSHO: TDataSource;
    ADOQSHONazvanie: TStringField;
    ADOQSHOFIO: TStringField;
    ADOQSHOFIO2: TStringField;
    ADOQSHOPloshad: TFloatField;
    ADOQSHOVid: TStringField;
    ADOQSHOStavka: TFloatField;
    ADOQSHOSumma: TFloatField;
    ADOQSHONPProsh: TFloatField;
    ADOQSHOOplata: TFloatField;
    ADOQSHOItigo: TFloatField;
    ADOQSHONPSled: TFloatField;
    ADOQSHOData_oplati: TDateTimeField;
    ADOQNSHO: TADOQuery;
    DSQNSHO: TDataSource;
    ADOQNSHONazvanie: TStringField;
    ADOQNSHOFIO: TStringField;
    ADOQNSHOFIO2: TStringField;
    ADOQNSHODop_deat: TStringField;
    ADOQNSHOPloshad: TFloatField;
    ADOQNSHOStavka: TFloatField;
    ADOQNSHONPProsh: TFloatField;
    ADOQNSHOSumma: TFloatField;
    ADOQNSHOItogo: TFloatField;
    ADOQNSHOOplata: TFloatField;
    ADOQNSHOData_oplati: TDateTimeField;
    ADOQNSHONPSled: TFloatField;
    ADOQNSHOAdres: TStringField;
    ADOQ4O: TADOQuery;
    DSQ4O: TDataSource;
    ADOQ4ONazvanie: TStringField;
    ADOQ4OAdres: TStringField;
    ADOQ4OFIO: TStringField;
    ADOQ4OFIO2: TStringField;
    ADOQ4ODop_deat: TStringField;
    ADOQ4OViruchka: TFloatField;
    ADOQ4OSumma_NDS: TBCDField;
    ADOQ4OViruchka_bez_NDS: TBCDField;
    ADOQ4OStavka: TBCDField;
    ADOQ4OSumma: TBCDField;
    ADOQ4ONPProsh: TBCDField;
    ADOQ4OItogo: TBCDField;
    ADOQ4OOplata: TBCDField;
    ADOQ4OData_oplati: TDateTimeField;
    ADOQ4ONPSled: TBCDField;
    ADOQPUO: TADOQuery;
    ADOQPUOSelo: TStringField;
    ADOQPUOUlisa: TStringField;
    ADOQPUONomer_doma: TStringField;
    ADOQPUOStavka: TFloatField;
    ADOQPUOSumma: TFloatField;
    ADOQPUONPProsh: TFloatField;
    ADOQPUOItogo: TFloatField;
    ADOQPUOOplocheno: TFloatField;
    ADOQPUONPSled: TFloatField;
    ADOQPUOData_oplati: TStringField;
    ADOQPUOHozain: TStringField;
    ADOQPUOKategoria_lgot: TStringField;
    ADOQPUOPriusad_uchastok: TFloatField;
    ADOQPUOID_Selo: TAutoIncField;
    ADOQPUOID_Ulisi: TAutoIncField;
    ADOQPUOID_Nomer_doma: TAutoIncField;
    DSQPUO: TDataSource;
    procedure DataModuleCreate(Sender: TObject);

  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DataModule1: TDataModule1;
  ID_S:Integer;
  ID_U:Integer;
  ID_D:Integer;


implementation

{$R *.dfm}



procedure TDataModule1.DataModuleCreate(Sender: TObject);
begin
  ADOUlisi.Active:=true;

   ADOSelo.Active:=true;
    ADOJiteli.Active:=true;
     ADOHoz_kniga.Active:=true;
   ADOLgoti.Active:=true;
       ADONasionalnost.Active:=true;
        ADOObrazovanie.Active:=true;
         ADOKrest_hoz.Active:=true;
          ADONalogR.Active:=true;


 ADOSNalog4.Active:=true;
  ADOVid_zemli.Active:=true;
 ADOHoz_subekt.Active:=true;
    ADOVid_Hoz_subekta.Active:=true;
     ADOVid_deatelnosti.Active:=true;
      ADONomer_doma.Active:=true;
       ADONalogNSH.Active:=true;
        ADONalog4.Active:=true;
       ADOSNalogMF.Active:=true;
          ADONalogPU.Active:=true;
           ADOSNalogPU.Active:=true;
            ADOSNalogSH.Active:=true;


  ADONalogSH.Active:=true;
    ADOVid_avto.Active:=true;
     ADOSrok_ekspluatasii_avto.Active:=true;
        ADOSNalogMU.Active:=true;
          ADONalogMF.Active:=true;
           ADOStavka_avto.Active:=true;
              ADOSNalogAvto.Active:=true;
                ADOMarka_avto.Active:=true;
                 ADOAvto.Active:=true;
                    ADONalogAvto.Active:=true;



   ADOSNalogR.Active:=true;
     ADOSNalogNSH.Active:=true;
      ADONalogMU.Active:=true;
         ADOUlisi.Active:=true;
           ADOUlisi.Active:=true;
             ADOUlisi.Active:=true;
               ADOUlisi.Active:=true;
                 ADOUlisi.Active:=true;
                   ADOUlisi.Active:=true;
                     ADOUlisi.Active:=true;
                       ADOUlisi.Active:=true;





end;

end.
